In [29]:
import os
os.chdir("/home/sizheree/workspace/code/Parallel_Program/lab4")

In [30]:
with open("./output.txt", "r") as fp:
    data = fp.read()

In [31]:
data1 = data[data.find("DEBUG 限制矩阵"):]

In [32]:
import io

In [33]:
f = io.StringIO(data1)

In [34]:
def getmatrix(n):
    while(1):
        if(f.readline().strip()=="DEBUG 限制矩阵"):
            res1 = []
            res2 = []
            for i in range(n):
                res1.append(f.readline())
            f.readline()
            for i in range(n):
                res2.append(f.readline())
            yield res1,res2
    

In [35]:
g10 = getmatrix(14)

In [36]:
with open("./input.txt", "r") as fp:
    fp.readline()
    lmaps = fp.readlines()

In [37]:
br = []
lp = []
lmap = []
import numpy as np
brs,lps = next(g10)
for i in brs:
    br.append([int(x) for x in i.strip().split('  ')])
for i in lps:
    lp.append([int(x) for x in i.strip().split('  ')])
for i in lmaps:
    lmap.append([int(x) for x in i.strip().split(' ')])
    

lp = np.array(lp)
br = np.array(br)
lmap = np.array(lmap)
print(lp,"\n", br, "\n", lmap)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]] 
 [[0 1 0 1 0 1 0 0 1 0 1 1 3 0]
 [0 0 0 0 1 0 0 0 0 0 3 3 0 1]
 [1 0 0 0 0 0 0 0 0 1 1 3 0 0]
 [1 3 1 1 0 0 0 0 0 0 1 0 0 1]
 [3 0 1 0 0 1 1 0 1 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 1 0 1 0 0 0 1]
 [0 1 0 0 0 1 0 1 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 1 0 1 0 0 1 0 1 0 1 0]] 
 [[-2 -1 -2  3 -2 -1 -2 -2 -1 -2  1  0 -2 -2]
 [-2 -2 -2 -2  2 -2 -2 -2 -2 -2 -2 -2 -2 -1]
 [-1 -2 -2 -2 -2 -2 -2 -2 -2  1  0 -

In [38]:
%matplotlib

Using matplotlib backend: Qt5Agg


In [39]:
# %matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import colors
import matplotlib.patches as patches
import numpy as np


In [40]:
fig = plt.figure(figsize=(8,8))
axe = plt.gca()
plt.ioff()
# br = []
# lp = []
# lmap = []
# brs,lps = next(g10)
# for i in brs:
#     br.append([int(x) for x in i.strip().split('  ')])
# for i in lps:
#     lp.append([int(x) for x in i.strip().split('  ')])
# for i in lmaps:
#     lmap.append([int(x) for x in i.strip().split(' ')])
# lp = np.array(lp)
# br = np.array(br)
# lmap = np.array(lmap)

# for i in range(lp.shape[0]):
#     for j in range(lp.shape[1]):
#         if lp[i][j]>0:
#             axe.add_patch(patches.Rectangle((i, j), 1, 1, color="y"))
            
# for i in range(br.shape[0]):
#     for j in range(br.shape[1]):
#         if br[i][j]==1:
#             axe.add_patch(patches.Rectangle((i, j), 1, 1, color="black"))
#             if(lmap[i][j]>=0):
#                 axe.annotate("%d"%lmap[i][j], (i+0.5, j+0.5))
#                 axe.text(i+0.2, j+0.8, "%d"%lmap[i][j], fontsize=20, color="white")
#         elif br[i][j]==2:
#             axe.add_patch(patches.Circle((i+0.5, j+0.5), 0.3, color="blue"))
            

#     键盘模式
def onkey(event):
    global mode
    axe = plt.gca()
    plt.cla()
    axe.set_xticks(np.arange(0, 15, 1))
    axe.invert_yaxis()
    axe.set_yticks(np.arange(0, 15, 1))
    plt.grid()
    if event.key == "b":
        print("hhh")
        br = []
        lp = []
        lmap = []
        brs,lps = next(g10)
        for i in brs:
            br.append([int(x) for x in i.strip().split('  ')])
        for i in lps:
            lp.append([int(x) for x in i.strip().split('  ')])
        for i in lmaps:
            lmap.append([int(x) for x in i.strip().split(' ')])
        lp = np.array(lp)
        br = np.array(br)
        lmap = np.array(lmap)
        for i in range(lp.shape[0]):
            for j in range(lp.shape[1]):
                if lp[i][j]>0:
                    axe.add_patch(patches.Rectangle((j, i), 1, 1, color="y"))

        for i in range(br.shape[0]):
            for j in range(br.shape[1]):
                if br[i][j]==1:
                    axe.add_patch(patches.Rectangle((j, i), 1, 1, color="black"))
                    if(lmap[i][j]>=0):
#                         axe.annotate("%d"%lmap[i][j], (i+0.5, j+0.5))
                        axe.text(j+0.2, i+0.8, "%d"%lmap[i][j], fontsize=20, color="white")
                elif br[i][j]==2:
                    axe.add_patch(patches.Circle((j+0.5, i+0.5), 0.3, color="blue"))
                elif br[i][j]==3:
                    axe.add_patch(patches.RegularPolygon((j+0.5, i+0.5), 3, radius=0.5, color="red"))
        
        plt.show()
    elif event.key == "q":
        mode = "quit"
        
fig.canvas.mpl_connect('key_press_event', onkey)


plt.show()


hhh
hhh
hhh
hhh
hhh
hhh
